name: aeson-flowtyped
license: BSD3
license-file: LICENSE
author: Mike Ledger <mike@quasimal.com>
category: Web
version: 0.6.0
dependencies:
- base >= 4.9
- vector
- text
- aeson >= 0.8
library:
  source-dirs: src
  exposed-modules: Data.Aeson.Flow
  dependencies:
  - time
  - unordered-containers
  - containers
  - reflection
  - recursion-schemes
  - wl-pprint
  - free
  - scientific
  ghc-options: -Wall -threaded -O2

tests:
  aeson-flowtyped:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - aeson-flowtyped
    - tasty
    - tasty-hunit
