name: aeson-flowtyped
license: BSD3
description: Create Flow type definitions from Haskell data types.
synopsis: Create Flow type definitions from Haskell data types.
license-file: LICENSE
author: Mike Ledger <mike@quasimal.com>
maintainer: mike@quasimal.com
category: Web
version: 0.7.5
dependencies:
- base >= 4.9 && <4.11
- aeson >= 0.8
- vector
- text
- recursion-schemes
library:
  source-dirs: src
  exposed-modules: Data.Aeson.Flow
  dependencies:
  - time
  - unordered-containers
  - containers
  - reflection
  - wl-pprint
  - free
  - scientific
tests:
  aeson-flowtyped:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - aeson-flowtyped
    - tasty
    - tasty-hunit
    - unordered-containers

github: mikeplus64/aeson-flowtyped
